### ISSUE TITLE
possible to set memcache 'expire' on locks?

### ISSUE THREAD

**Issue by reedgz** [arvenil/ninja-mutex#12]
Hi, First of all thanks for the great library!  Here I have some problems with un-released locks. 

I am calling many 3rd party libraries between lock & release.  Very occasionally I could get a fatal crash that the lock is never cleaned up.

My process typically takes 3~5 sec to complete, is it possible to set an expire value for the lock?   
E.g. 60 sec, so it is not locked forever.

I could see the alternative maybe using flock so file system handles it...  

My code is very simple like this:
```php
$mutex = new Mutex('very-critical-stuff', $lock);
if ($mutex->acquireLock(1000)) {
    // calling many 3rd party libraries.
    // !!! Fatal error crash.
    // the lock is never released
    $mutex->releaseLock();
} else {
    throw new Exception('Unable to gain lock!');
}
```

**Comment by arvenil** [comment]
https://github.com/arvenil/ninja-mutex/pull/13 Will that work for you?

**Comment by reedgz** [comment]
@arvenil You are awesome!     
I carefully read everything you wrote in the fix.  It will work for me but I wouldn't recommend it for anyone else.  I should use an expire time like 100x of the typical processing time.

It is up to you to merge this into master branch.  The potential racing problem is pretty hard to deal with.    I don't want people complain about ninjia-mutex because of this change; changing my code to use flock or mySQL is probably easier.

**Comment by arvenil** [comment]
Awesome :)

No worries, the `->setExpiration()` method is optional, by default there is no expiration. Just a warning that it may be dangerous should be enough.

Thanks for your issue report! :)

**Comment by arvenil** [comment]
Resolved by https://github.com/arvenil/ninja-mutex/releases/tag/0.5.0
