### ISSUE TITLE
timeout parameter is never used

### ISSUE THREAD

**Issue by AidasK** [arvenil/ninja-mutex#15]
Timeout feature foes not work in any of implementations. 
https://github.com/arvenil/ninja-mutex/blob/master/src/NinjaMutex/Mutex.php#L56

Only one Flock uses it to set blocking lock at https://github.com/arvenil/ninja-mutex/blob/master/src/NinjaMutex/Lock/FlockLock.php#L37

Shouldn't mutex do a loop for a timeout to expire?

**Comment by arvenil** [comment]
https://github.com/arvenil/ninja-mutex/blob/master/src/NinjaMutex/Lock/LockAbstract.php#L68-L94

Why you think timeout doesn't work? Show me your code please.

There is even a test for it:
https://github.com/arvenil/ninja-mutex/blob/master/tests/NinjaMutex/MutexLocksTest.php#L121-L136

**Comment by AidasK** [comment]
My bad, sorry

**Comment by arvenil** [comment]
No worries. Great it worked for you! :)
