### ISSUE TITLE
Multiple connections MySQL Lock

### ISSUE THREAD

**Issue by marcojanssen** [arvenil/ninja-mutex#17]
I wanted to lock a specific record in a data storage which are identified by UUID. To acquire the lock we do it like the following pseudo code:

```php
if ( ! $this->lock->acquireLock($UUID)) {
   //logic
}
```

However by doing so we create a PDO connection for each UUID we want to lock since the MySqlLock sets up PDO by itself and stores a connection based on the name used for acquiring the lock (the UUID in this use case)

Looking at the other lock adapters we always inject the connection instead, is the mysql different by intention or just something we need to implement differently?

**Comment by marcojanssen** [comment]
Seems that locking is for each connection, still doesn't seem to properly disconnect when destructing

**Comment by marcojanssen** [comment]
Possible fix

https://github.com/arvenil/ninja-mutex/pull/18

**Comment by arvenil** [comment]
The problem with MySQL adapter is that you can only acquire one lock per connection. You can't on the same connection acquire two different locks. Any attempt to acquire another lock will result in releasing first lock. This is not a problem with this library, pdo or php - it's how this works in MySQL.
https://dev.mysql.com/doc/refman/5.0/en/miscellaneous-functions.html#function_get-lock

(well, it looks like they changed/fixed that in MySQL 5.7.5 https://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_get-lock and now multiple locks can be gained on one connection)

About, not closing connection - at first look it looks like you might be right, I'm curious when I messed that up. How did you figure out that connections are not getting closed?

**Comment by marcojanssen** [comment]
We saw the number of mysql connections quickly rise when we released the latest update of our software which had some command handling loading aggregates with mysql locking in it. So a pure we hit it when it went live on production :)

**Comment by marcojanssen** [comment]
Can confirm that the fix is working, long processes (like our workers) now close the connections when the lock is released

**Comment by marcojanssen** [comment]
@arvenil So could you merge the fix?

**Comment by arvenil** [comment]
Thanks again! Released as 0.5.1
