### ISSUE TITLE
How can I achieve the same behavior than the MySQL GET_LOCK() command?

### ISSUE THREAD

**Issue by Seb147** [arvenil/ninja-mutex#20]
For this example, I'm using the Memcached backend, and a timeout value of 0.

With MySQL GET_LOCK(), if a PHP script terminates before releasing explicitely the lock (Fatal Error for example), it is released anyway. However, with your library, if a PHP script terminates before releasing the lock, it can never get it again, because Memcached don't delete the lock automatically.

**Comment by arvenil** [comment]
> How can I achieve the same behavior than the MySQL GET_LOCK() command?

You can't. This library allows you to use different backends for the purpose of locking (memcache, redis, mysql, flock). Memcache and redis have the disadvantage you've mentioned. In certain cases it may lead to not releasing lock e.g. when script dies or when there is no connection to memcache or redis storage. Mysql and flock backend doesn't have that drawback.

Just for the clarification. Memcache backend has a __desctructor that releases the lock if it wasn't explicitly released, and while I've tested this it worked on certain fatal errors (destructor was still run and so the lock was released). But again, don't expect it to work on all fatal errors. If you want this to work 100% of times use mysql or flock backend (which has other disadvantages :)). Sadly there is no perfect solution :)

**Comment by Seb147** [comment]
Ok, thanks for your answer. I'll try to find a trick to make it work the way I need :)

**Comment by arvenil** [comment]
Hey, let me know what "trick" you've used :)

**Comment by Seb147** [comment]
I made a pull request with my fix, so you can check :)
